#!/bin/bash

# Instalar yay
yay() {
    pacman -S --needed git base-devel go --noconfirm

		rm -r ./yay
    git clone https://aur.archlinux.org/yay.git

    USER=$(logname)
    chown -R $USER:users ./yay

    cd ./yay
    sudo -u $USER makepkg -si --noconfirm

    if command -v yay &> /dev/null; then
        echo "yay se ha instalado correctamente."
    else
        echo "Hubo un problema al instalar yay."
    fi
}

# Instalar programas basicos
base() {
	# Paquetes de personalizacion
	yay -S lightdm lightdm-gtk-greeter jq brightnessctl polybar bspwm sxhkd picom nitrogen bashtop python-psutil alacritty numlockx light-locker glib2 gvfs lxappearance brightnessctl pavucontrol pamixer lolcat thunar zip file-roller thunar-archive-plugin --noconfirm
	# Fuentes
	yay -S ttf-jetbrains-mono ttf-cascadia-code ttf-hack ttf-joypixels otf-font-awesome --noconfirm
}

xfce() {
	yay -S jdk17-openjdk xfce4-notifyd xfce4-power-manager xfce4-clipman-plugin blueberry xfce4-screenshooter --noconfirm
}

configure_touchpad() {
  sudo tee /etc/X11/xorg.conf.d/30-touchpad.conf > /dev/null << 'EOF'
Section "InputClass"
    Identifier "devname"
    Driver "libinput"
    MatchIsTouchpad "on"
    Option "Tapping" "on"
    Option "NaturalScrolling" "true"
EndSection
EOF
}

user_zsh() {
	sudo pacman -S zsh zsh-completions zsh-autosuggestions --noconfirm
	
	sudo pacman -S curl git --noconfirm

	sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

	yay -S --noconfirm zsh-theme-powerlevel10k-git

	sudo pacman -S powerline-common awesome-terminal-fonts --noconfirm

	yay -S --noconfirm ttf-meslo-nerd-font-powerlevel10k

	git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting

	git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
}

all_base() {
	yay
	base
	xfce
	configure_tochpad
}

all() {
	all_base
}

# Verificar si se está ejecutando como root
#if [ "$EUID" -ne 0 ]; then
  #echo "Por favor, ejecuta el script como root o con sudo."
  #exit 1
#fi

# Verificar que se pasó al menos un argumento
if [ "$#" -eq 0 ]; then
  echo "Uso: sudo $0 <funcion_1> <funcion_2> ... <funcion_n>"
	echo ""
	echo "Opciones de instalacion:"
	echo "- yay                   Instala yay para paquetes Arch."
	echo "- base                  Instala paquetes basicos que uso."
	echo "- xfce                  Instala paquetes extra que se puede usar en Arch."
	echo "- configure_touchpad    Configura el touchpad del sistema."
	echo "- all_base              Instala todos los paquetes base."
	echo "- all                   Instala todo incluido la base."
  exit 1
fi

# Ejecutar las funciones pasadas como argumentos
for func in "$@"; do
    if declare -f "$func" > /dev/null; then
        echo "Ejecutando $func..."
        $func
    else
        echo "La función '$func' no está definida."
    fi
done
